FROM alpine:3.22

RUN apk add --no-cache \
    bash bash-completion iproute2 iputils traceroute procps \
    grpc-dev thrift-dev boost-dev libpcap-dev nanomsg-dev python3 \
    gmp

COPY ./clab-node/node.bashrc /root/.bashrc
COPY ./repos/install/ /usr/local/

# p4
COPY ./clab-node/basic.p4 /root/basic.p4

WORKDIR /root