services:
  containerlab:
    build:
      context: .
      dockerfile: Dockerfile.containerlab
    privileged: true
    network_mode: host
    pid: host
    volumes:
      # Required for containerlab to access Docker daemon on the host.
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount host kernel modules (optional but recommended).
      - /lib/modules:/lib/modules
      # ==============================
      - ./topo.clab.yml:/root/topo.clab.yml
      - ./clab-node:/root/clab-node
      # ===============================
      - ./repos:/root/repos
      - ./repos/build:/root/repos/build
      - ./repos/install:/root/repos/install
    entrypoint: ["tail", "-f", "/dev/null"]