services:
  containerlab:
    build:
      context: .
      dockerfile: Dockerfile.containerlab
    privileged: true
    network_mode: host
    pid: host
    volumes:
      # Required for containerlab to access Docker daemon on the host.
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount host kernel modules (optional but recommended).
      - /lib/modules:/lib/modules
      - ./topo.clab.yml:/root/containerlab/topo.clab.yml
      - ./Dockerfile.node:/root/containerlab/Dockerfile.node
      - ./entrypoint_node.sh:/root/containerlab/entrypoint_node.sh
      - ./build:/root/containerlab/build
      - ./PI:/root/containerlab/PI
      - ./behavioral-model:/root/containerlab/behavioral-model
      - ./p4c:/root/containerlab/p4c
    entrypoint: ["tail", "-f", "/dev/null"]