FROM debian:bookworm AS builder

COPY ./entrypoint_dev.sh /tmp/entrypoint.sh
RUN cat /tmp/entrypoint.sh >> /root/.bashrc && \
    rm /tmp/entrypoint.sh

WORKDIR /root

ENV PI_DEV_DEPS="\
    autoconf libtool build-essential pkg-config\
    protobuf-compiler-grpc libgrpc++-dev libboost-thread-dev"
ENV BMV2_DEV_DEPS="\
    autoconf libtool g++ thrift-compiler \
    libthrift-dev libnanomsg-dev libgmp-dev \
    libpcap-dev protobuf-compiler-grpc libboost-thread-dev \
    make libboost-program-options-dev libboost-filesystem-dev \
    libgrpc++-dev"
ENV P4C_DEV_DEPS="\
    cmake python3 flex bison git libboost-iostreams-dev"
RUN apt-get update && \
    apt-get install -y $PI_DEV_DEPS $BMV2_DEV_DEPS $P4C_DEV_DEPS